DEBUG: True
seed: ~

# 实验设置
EXP_NAME: 'Auto lens design'

# # 镜头目标示例 1（相机镜头）
# foclen: 85.0
# fov: 40.0
# fnum: 4.0
# bfl: 18.0
# thickness: 120.0
# surf_list: [["Spheric", "Spheric"], ["Spheric", "Spheric"], ["Spheric", "Spheric", "Spheric"], ["Aperture"], ["Spheric", "Spheric", "Spheric"], ["Spheric", "Aspheric"], ["Spheric", "Aspheric"]]
# lrs: [1e-3, 1e-4, 1e-2, 1e-4]

# 镜头目标示例 2（手机镜头）
foclen: 6.1
fov: 85.0
fnum: 1.9
bfl: 0.97
thickness: 7.3
surf_list: [["Aperture"], ["Aspheric", "Aspheric"], ["Aspheric", "Aspheric"], ["Aspheric", "Aspheric"], ["Aspheric", "Aspheric"], ["Aspheric", "Aspheric"]]
lrs: [1e-3, 1e-3, 1e-2, 1e-3]

# # 镜头目标示例 3（相机镜头）
# foclen: 35.0
# fov: 50.0
# fnum: 2.0
# bfl: 18.0
# thickness: 120.0
# surf_list: [["Spheric", "Spheric"], ["Spheric", "Spheric"], ["Spheric", "Spheric"], ["Spheric", "Spheric"], ["Aperture"], ["Spheric", "Spheric"], ["Spheric", "Spheric"], ["Spheric", "Spheric"], ["Spheric", "Spheric"]]
# # lrs: [1e-3, 1e-3, 0.0, 0.0]
# lrs: [1e-4, 1e-4, 0.0, 0.0]
#
# # 镜头目标示例 4（手机镜头）
# foclen: 5.0
# fov: 90.0
# fnum: 2.0
# bfl: 1.5
# thickness: 10.0
# surf_list: [["Aperture"], ["Aspheric", "Aspheric"], ["Aspheric", "Aspheric"], ["Aspheric", "Aspheric"], ["Aspheric", "Aspheric"], ["Aspheric", "Aspheric"], ["Aspheric", "Aspheric"]]
# lrs: [1e-3, 1e-3, 1e-2, 1e-3]

# # 镜头目标示例 5（相机镜头）
# foclen: 30.0
# fov: 70.0
# fnum: 2.8
# bfl: 18.0
# thickness: 50.0
# surf_list: [["Aspheric", "Aspheric"], ["Aperture"], ["Aspheric", "Aspheric"], ["Aspheric", "Aspheric"], ["Aspheric", "Aspheric"], ["Aspheric", "Aspheric"]]
# lrs: [1e-3, 1e-3, 1e-2, 1e-4]
